[package]
name = "spacecan-firmware"
version = "0.1.0"
edition = "2024"

[lib]
test = false

[[bin]]
name = "firmware"
path = "src/main.rs"
test = false

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"
embedded-hal = "0.2"
nb = "1.0"
stm32g0xx-hal = { version = "0.2", features = ["stm32g071", "i2c-blocking"], default-features = false }
spacecan = { path = "../spacecan", features = ["defmt"] }
bxcan = "0.7"
fugit = "0.3"
defmt = "0.3"

[package.metadata.cortex-m-rt]
memory.x = "memory.x"

